# default values ...
use_seeds: false
connection_threshold: 0.06
min_points_per_group: 15
leg_reliability_limit: 0.7
publish_legs: True
publish_people: True
publish_leg_markers: True
publish_people_markers: True
no_observation_timeout: 0.5
max_second_leg_age: 1.0
max_track_jump: 1.0
max_meas_jump: 0.75
leg_pair_separation: 1.0
fixed_frame: /robot5/odom
kalman_p: 4
kalman_q: .002
kalman_r: 10
