footprint: [[-0.2, -0.3], [-0.2, 0.3], [1.7, 0.3], [1.7, -0.3]] # previously defined ad 1.9, for citi trucks
global_frame: map_laser2d
height: 8
inflation_layer: {cost_scaling_factor: 10, enabled: true, inflation_radius: 2.5}
map_type: costmap
obstacle_layer:
  combination_method: 1
  enabled: true
  inflation_radius: 0.2
  nav_laser_scan_sensor: {clearing: true, data_type: LaserScan, marking: true, topic: /robot4/sensors/laser2d_top_fil}
  observation_sources: safe_laser_scan_sensor nav_laser_scan_sensor
  obstacle_range: 3.0
  raytrace_range: 3.5
  safe_laser_scan_sensor: {clearing: true, data_type: LaserScan, marking: true, topic: /robot4/sensors/laser2d_floor_fil}
  track_unknown_space: false
plugins:
- {name: static_layer, type: 'costmap_2d::StaticLayer'}
- {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
- {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
publish_frequency: 2.0
resolution: 0.1
robot_base_frame: robot4/base_link
rolling_window: true
static_layer: {enabled: true, global_frame: /map_laser2d, map_topic: /maps/map_laser2d}
static_map: false
transform_tolerance: 0.2
update_frequency: 5.0
width: 8
inflation_layer: {cost_scaling_factor: 10.0, enabled: true, inflation_radius: 2.5}