grid_map_topic: /constrain_maps_node/grid_map
grid_map_visualizations:
  - name: constr0
    type: occupancy_grid
    params:
     layer: "0"
     data_min: 0
     data_max: 1.0
  - name: constr1
    type: occupancy_grid
    params:
     layer: "1"
     data_min: 0
     data_max: 1.0
  - name: constr2
    type: occupancy_grid
    params:
     layer: "2"
     data_min: 0
     data_max: 1.0
  - name: constr3
    type: occupancy_grid
    params:
     layer: "3"
     data_min: 0
     data_max: 1.0
  - name: global_constrain_mpc
    type: occupancy_grid
    params:
     layer: "global_constrain"
     data_min: 0.0
     data_max: 0.25
