static_map: true
track_unknown_space: false # mfc: I think this param has no use here ...
always_send_full_costmap: true
footprint: [[-0.2, -0.3], [-0.2, 0.3], [1.7, 0.3], [1.7, -0.3]] # previously defined ad 1.9, for citi trucks
global_frame: "/map_laser2d"
robot_base_frame: "base_footprint_ground_truth"
publish_frequency: 3.0
update_frequency: 5.0
plugins:
  - {name: static_map, type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}

static_map:
  track_unknown_space: true
  map_topic: "/maps/map_laser2d"
  use_maximum: true
  trinary_costmap: false

obstacles_laser:
  observation_sources: laserScanner
  laserScanner: {data_type: LaserScan, clearing: true, marking: true, topic: /robot3/sensors/laser2d_floor/human_filtered, sensor_frame: /robot3/laser2d_floor_link, obstacle_range: 20.0, raytrace_range: 21, inf_is_valid: true}
  
